language: go
go:
- 1.5
- 1.6
- 1.7
- 1.8
- 1.9
- 1.10
- tip
install:
- npm install gulp
- make deps
script:
- make lint
- make test
- make build
notifications:
  slack:
    secure: oNlkgQYC3BRmQ49wr4lhAB/16AqsTfOWp7kHfaEnmQ728mHRLh+NnT1YM6voy1a0ibHpTdo2xva0fQUBgGUsEkNWLgXHmoxLHgaewykKI0KiRE1pvbmuw/cjO0RWfgZJUKzcm1u60HjdY4hD0niKWqCdtLaCvu8znd9bwXYBq7w=
